M48
; DRILL file {KiCad 7.0.1} date Fri May 10 16:10:39 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-10T16:10:39-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C0.0394
%
G90
G05
T1
X5.0Y-4.0
T2
X4.9Y-5.3
X5.1Y-5.3
T0
M30
